name: Test and build preview packages

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
    - 'master'

jobs:
  buildDockerContainers:
    runs-on: "ubuntu-latest"
    if: test -n $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e Dockerfile -e "scripts/buildsystem/debian" -e build_debian_docker_image)
    env:
      DOCKER_ID: 'cmcquinn'
      IMAGE_NAME: 'mk-hal-cross-builder'
    strategy:
      matrix:
        image_tag: [amd64_8, amd64_9, amd64_10, arm64_9, arm64_10, armhf_8, armhf_9, armhf_10, i386_8, i386_9, i386_10]

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
          path: mkhal

    - name: Build Docker images
      run: scripts/build_debian_docker_image -i ${{ env.DOCKER_ID}} -r ${{ env.IMAGE_NAME }} -t ${{ matrix.image_tag }}
      working-directory: mkhal

    - name: Login to Docker Hub
      run: docker login -u ${{ env.DOCKER_ID }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Push images to Docker Hub
      run: docker push ${{ env.DOCKER_ID }}/${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}
        
  testMachinekitHAL:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'eryaf/mk-cross-builder'
    strategy:
      matrix:
        image_tag: [amd64_8, amd64_9, amd64_10]

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.sha }}
        path: to_build

    - name: Test Machinekit code on AMD64
      run: scripts/build_docker -i ${{ env.IMAGE }} -t ${{ matrix.image_tag }} -c test
      working-directory: ./to_build

  buildMachinekitHALPackages:
    runs-on: ubuntu-latest
    needs: buildDockerContainers
    env:
      IMAGE: 'eryaf/mk-cross-builder'
    strategy:
      matrix:
        # Jessie does not have a ARM64 build
        image_tag: [amd64_8, amd64_9, amd64_10, arm64_9, arm64_10, armhf_8, armhf_9, armhf_10, i386_8, i386_9, i386_10]

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.sha }}
        path: to_build/mkhal

    - name: Build Machinekit-HAL .deb package
      run: scripts/build_docker -i ${{ env.IMAGE }} -t ${{ matrix.image_tag }} -c deb
      working-directory: ./to_build/mkhal

    - name: Print built files
      run: find . -depth -not \( -path "." -or -path "./mkhal" -or -path "./mkhal/*" \) -print0 | xargs -0 -I '{}' ls --color -d '{}'
      working-directory: ./to_build

    - name: Create output directory 
      run: mkdir ./machinekit-hal-debian
    
    - name: Copy built files into output directory
      run: find ./to_build -depth -not \( -path "." -or -path "./to_build" -or -path "./to_build/mkhal" -or -path "./to_build/mkhal/*" \) -print0 | xargs -0 -t -I '{}' cp -v '{}' ./machinekit-hal-debian

    - name: Upload the built artifacts
      uses: actions/upload-artifact@v1
      with:
        name: machinekit-hal-debian-${{ matrix.image_tag }}-${{ github.sha}}
        path: machinekit-hal-debian
       